name: eqraa
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  # DateTime
  jiffy: ^5.0.0
  #  intl: ^0.17.0
  http: ^0.13.4
  # Images
  cached_network_image: ^3.3.1
  image_picker: ^0.7.2+1
  # Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1

  #   Firebase And Notification
  firebase_messaging: ^14.7.20
  firebase_core: ^2.27.1
  flutter_local_notifications: ^9.5.3+1
  firebase_analytics: ^10.8.10
  #  cloud_firestore: ^3.1.9
  # Local Data Cache
  #  sqflite: ^2.0.2
  shared_preferences: ^2.0.3
  path: ^1.8.0
  # Qrcode
  qr_flutter: ^4.0.0
  scan: ^1.6.0
  grouped_list: ^4.2.0
  url_launcher: ^6.1.2
  dropdown_search: ^3.0.1
  badges: ^2.0.2
  # Icon
  flutter_svg: ^0.23.0
  font_awesome_flutter: ^10.1.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  # Google Auth
  #  google_sign_in: ^5.3.1
#  device_preview: ^0.7.5
  flutter_screenutil: ^5.9.0
  responsive_builder: ^0.4.2
  image_pickers: ^2.0.0+2
  flutter_otp_text_field: ^1.1.0+2
  lottie: ^2.2.0
  awesome_dialog: ^3.0.2
  cool_alert: ^2.0.1
  #  rating_dialog: ^2.0.4
  #  flutter_rating_bar: ^4.0.1
  flutter_lints: ^2.0.1
  shimmer: ^3.0.0
  #  flutter_ringtone_player: ^3.0.0
  #  vibration: ^1.7.7
  audioplayers: ^6.0.0
  connectivity_plus: ^5.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_svg_provider: ^0.1.9
  modal_bottom_sheet: ^3.0.0
  # PDF
  flutter_cached_pdfview: ^0.4.2
  flutter_pdfview: ^1.0.4+4
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  file_picker: ^4.6.1
  syncfusion_flutter_pdfviewer:
  sizer: any
  flutter_secure_storage: ^8.1.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: true
  ios: true
  generate: false
  image_path: "assets/logo.png"
  min_sdk_android: 21

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/lottie/
    - assets/lottie/onboarding/
    - assets/
    - assets/pdf/
    - assets/pdf/sera.pdf
    - assets/pdf/doaa.pdf
    - assets/pdf/hart.pdf
    - assets/pdf/shmail.pdf


    # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
